name:                   conv
version:                0.0.0
synopsis:               Convolutional neural networks
description:            ""

author:                 "Bogdan Penkovsky"
maintainer:
category:               AI
extra-source-files:
- README.md

dependencies:
- base                    >= 4.7 && < 4.13
- deepseq
- massiv                  >= 0.4.3.0 && < 0.5
- mwc-random
- streamly
- MonadRandom
- array
- backprop
- microlens
- microlens-th
# - splitmix

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fwarn-missing-signatures
  # - -Werror
  dependencies:
  - one-liner
  - one-liner-instances

executables:
  conv:
    main:             Main.hs
    source-dirs:      app
    ghc-options:
    - -O2
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N6
    dependencies:
    - massiv-io
    - mnist-idx
    - vector
    - transformers
    - deepseq
    - split
    - conv

benchmarks:
  default:
    main: Main.hs
    source-dirs: bench
    dependencies:
    - criterion
    - conv
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N6
